const refs = {
  teamList: document.querySelector('.team-list'),
  teamBtn: document.querySelector('.page-footer__action-btn'),
  lightboxBtn: document.querySelector('.lightbox-button'),

  movieList: document.querySelector('.main__section-list'),
  iconCloseBtn: document.querySelectorAll('.close-icon-container'),
  loginModal: document.querySelector('.login-page'),
  closeBtn: document.querySelector('.close-icon-container'),
  header: document.getElementById('page-header'),
  navMenu: document.getElementById('page-nav'),
  navLinks: document.querySelectorAll('.link-nav'),
  checkBox: document.querySelector('#theme-switch-toggle'),
  serchForm: document.querySelector('.search-form-js'),
  searchFormInput: document.querySelector('.search-form__input'),
  nextBtn: document.querySelector('.next-btn-js'),
  watchedBtn: document.querySelector('.watched'),
  queueBtn: document.querySelector('.queue'),
  errorMessage: document.querySelector('.search-form__field-error'),
  libraryPage: document.querySelector('.library-page-js'),
  libraryInfo: document.querySelector('.main__library-info'),
  headerContainer: document.querySelector('.header-container-js'),
  libraryContainer: document.querySelector('.library__section-list'),
  mainWrapper: document.querySelector('.main__section-wrapper'),
  glide: document.querySelector('.js-trending'),
  filmCards: document.querySelector('.js-film-cards'),
  openFooterModalBtn: document.querySelector('[data-footer-modal-open]'),
  closeFooterModalBtn: document.querySelector('[data-footer-modal-close]'),
  footerModal: document.querySelector('[data-footer-modal]'),
  openModalBtn: document.querySelector('[data-modal-open]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  modal: document.querySelector('[data-modal]'),
  filmInfoContainer: document.querySelector('.film-info'),
  addToWatchedBtn: document.querySelector('.add-watched'),
  addToQueueBtn: document.querySelector('.add-queue'),
  inputError: document.querySelector('.search-form__field-error'),
  watchedBtn: document.querySelector('.watched'),
  queuedBtn: document.querySelector('.queue'),
  filmImgContainer: document.querySelector('.film-img'),
};

export default refs;
